### ISSUE TITLE
Question: New refractoring of code?

### ISSUE THREAD

**Issue by sondreengebraten** [CodeReclaimers/neat-python#32] opened 2016-12-08 13:06 UTC
As part of the experiments I am doing I will be testing a fairly new algorithm called MAP-elites. This is a new search heuristic that would take the place of the GA in NEAT. I am hoping to be able to reuse large parts of this code in order to not have to re-implement the neural network itself. 

Would it be best to wait for the refractoring to be completed before doing this? I would be modifying the optimization part of neat-python effectively replacing the search algorithm completely. I would still like to keep the implementation of NN permutation, i.e. mutation and crossover.  If yes, how far along are you on this and is there anything I could do to help? 

Reference to MAP-elites: https://arxiv.org/abs/1504.04909

Best
Sondre

**Comment by CodeReclaimers** [comment] 2016-12-08 21:40
I think the refactoring is just about at a point where I should throw it out there and let people beat it up and tell me what I broke.  :)  I'll see if I can get all the examples working again and then just release it as 0.9, and then it would be great if you could try using it to implement MAP-elites.

I've been meaning to take a look at some of the recent literature, so I might as well see if there's any easy last-minute changes I can make that would make MAP-elites easier.

**Comment by CodeReclaimers** [comment] 2016-12-20 03:07
I updated an older example that uses a novelty archive and put it into the refactoring branch, not sure if this would be useful to you in the short term or not, but it's here: https://github.com/CodeReclaimers/neat-python/blob/refactor-and-simplify/examples/picture2d/non_interactive_novelty.py

**Comment by CodeReclaimers** [comment] 2017-01-05 15:59
Just in case you missed it, I merged the refactoring back into the main branch.  There is still some cleanup stuff to do, but I'll try not to change anything significant before releasing 0.9.

**Comment by sondreengebraten** [comment] 2017-01-06 08:13
Nice, thank you! Is there anything significant that is broken that I should know about?

**Comment by sondreengebraten** [comment] 2017-01-06 08:53
Have you thought any about the license you are using? Could I suggest you try something more standardized like an MIT license?

**Comment by CodeReclaimers** [comment] 2017-01-08 15:05
I'm actually not sure if it's permissible to change from BSD to MIT without either writing a "clean room" implementation from scratch or getting permission from all the committers.  The original library I started from was GPLv3; because GPLv3 is an unreadable mountain of legal text to me, and because the GPL->BSD conversion (as best I could tell) was an allowed transition, I switched to the simpler BSD license.

Is there a situation in which the BSD license causes unnecessary difficulty?  Right now I don't have a good feel for situations in which people might be using the code.

**Comment by CodeReclaimers** [comment] 2017-01-08 15:07
As to things being broken, the biggest things are the Izhikevich (spiking) neurons and the checkpointing not working.  There are undoubtedly bugs left to be found, and the documentation still hasn't caught up to the implementation in several respects.

**Comment by sondreengebraten** [comment] 2017-01-09 08:14
> Is there a situation in which the BSD license causes unnecessary difficulty? Right now I don't have a good feel for situations in which people might be using the code.

I did not know you were already on BSD. I read the license file (https://github.com/CodeReclaimers/neat-python/blob/master/LICENSE) and it appeared to me to be some kind of proprietary license. Maybe you could specify that this project is using a BSD license in the readme? As for situations where it might be difficult, I can't think of any as BSD seems very permissive.

Thank you for the update. I am writing a prototype for MAP-elites as we speak, I will let you know how it goes. MAP-elites would essentially replace the Population class and optimizer, would you say that would fit with neat-python or should it instead be an algorithm in for instance DEAP (https://github.com/DEAP/deap) using neat-python?

**Comment by CodeReclaimers** [comment] 2017-01-09 14:30
Ah, thanks--I'll make a note about the license in the README, I forgot the license text doesn't actually identify itself.

I think generally if you end up replacing the Population class when implementing an evolution scheme, odds are that you're doing something different enough from NEAT that it might be an easier fit in another framework.  Of course, it could also be the case that neat-python is still too clumsy. :) 

In any case, it might be interesting to see what you have to do in order to get MAP-elites working; maybe there are some changes we can make to neat-python to make it easier.  Ideally all you'd need to do is provide a custom reproduction type and maybe some machinery around the fitness evaluation, but it's always more complicated than I think when I go to do something like that.  So far the only similar thing I've tried is the novelty-based fitness: https://github.com/CodeReclaimers/neat-python/blob/master/examples/picture2d/evolve_novelty.py

Thanks for the mention of DEAP, I hadn't seen that project before.  Maybe it will turn out that NEAT is easier to implement in DEAP than in pure Python. ;)

**Closed** 2017-01-21 18:12 UTC
